const StatNames = [
    "AP",
    "MP",
    "Range",
    "Vitality",
    "Agility",
    "Chance",
    "Strength",
    "Intelligence",
    "Power",
    "Critical",
    "Wisdom",
    "AP Reduction",
    "AP Parry",
    "MP Reduction",
    "MP Parry",
    "Heals",
    "Lock",
    "Dodge",
    "Initiative",
    "Summons",
    "Prospecting",
    "Pods",
    "Damage",
    "Critical Damage",
    "Neutral Damage",
    "Earth Damage",
    "Fire Damage",
    "Water Damage",
    "Air Damage",
    "Reflect",
    "Trap Damage",
    "Power (traps)",
    "Pushback Damage",
    "% Spell Damage",
    "% Weapon Damage",
    "% Ranged Damage",
    "% Melee Damage",
    "Neutral Resistance",
    "% Neutral Resistance",
    "Earth Resistance",
    "% Earth Resistance",
    "Fire Resistance",
    "% Fire Resistance",
    "Water Resistance",
    "% Water Resistance",
    "Air Resistance",
    "% Air Resistance",
    "Critical Resistance",
    "Pushback Resistance",
    "% Ranged Resistance",
    "% Melee Resistance",
];

const IdForStatName = (name: string) => StatNames.findIndex(statName => statName === name)

export {
    StatNames,
    IdForStatName
}