# fly.toml app configuration file generated for dofusoptimiser on 2023-07-28T17:04:17+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dofusoptimiser"
primary_region = 'lhr'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
