# fly.toml file generated for dofusoptimiser on 2020-10-07T16:05:10+01:00

app = "dofusoptimiser"


[[services]]
  internal_port = 8000
  protocol = "tcp"

  [services.concurrency]
    type = "requests"
    hard_limit = 10
    soft_limit = 5

  [[services.ports]]
    handlers = ["http"]
    port = "80"
    force_https = true

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"
