[package]
name = "wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
dofus_set = { path = "../dofus_set" }

wasm-bindgen = "0.2"
console_error_panic_hook = "0.1" 
getrandom = { version = "0.2", features = ["js"] }
