[package]
name = "bench"
version = "0.1.0"
edition = "2021"

[dependencies]
dofus_characteristics = { path = "../dofus_characteristics" }
dofus_set = { path = "../dofus_set" }
dofus_items = { path = "../dofus_items" }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = "0.6"
