[package]
name = "dofus_characteristics"
version = "0.1.0"
edition = "2021"

[dependencies]
strum = { version = "0.26", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
thiserror = "2"
quote = "1"
proc-macro2 = "1"
