name: Website

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  merge_group:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: extractions/setup-just@v3
      - uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
            web/node_modules
            web/.next
          key: ${{ runner.os }}-next-${{ hashFiles('web/package-lock.json') }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Install wasm-pack
        run: npm install -g wasm-pack
      - name: Build wasm deps
        run: just prepare-web
      - name: Install npm deps
        run: npm ci
        working-directory: web
      - name: Lint
        run: npm run lint
        working-directory: web
      - name: Build
        run: npm run build
        working-directory: web
      - name: Upload website
        uses: actions/upload-pages-artifact@v3
        with:
          path: "web/out"
  deploy:
    name: Deploy website
    if: github.event_name == 'push'
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
